---
title: Glanzrock Productions
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
    status:
      in development: in development
      released: released
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: default
- scope:
    path: ''
    type: posts
  values:
    layout: post
- scope:
    path: ''
    type: projects
  values:
    layout: project
    categories:
    - Development
    - Production
    - Released
    tags:
    - Film
    - Comic
    - TV
    Credits:
      Writer: 
      Producer: 
      Director: 
    Main Image: "/uploads/stock-vector-two-vector-landscapes-with-silhouettes-of-forest-and-distant-mountain-ridges-illustration-of-632040476.jpg"
    Images:
    - 
    - 
email: bwalowitz@gmail.com
description: Glanzrock Productions is a film and television company, led by Andrew
  Davies Gans, that develops, produces, and finances projects at all stages of development.
baseurl: 
url: 
twitter_username: brandonwalowitz
github_username: bwalowitz
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
